update crowdin.yml, CHANGELOG.md, ro.json, it.json, nl.json and fr.js…
vtex/front.libs pull request #28
Opened 2020-11-16 18:04 UTC by camilavcoutinho

update romanian, italian, french and dutch translations.

2020-11-16 18:47 UTC, kevinch approved these changes

2020-12-09 18:50 UTC, lucasecdb commented
@camilavcoutinho I think you need to create another folder for the new version of the confirmation reasons package and update the messages in this new version, instead of updating an existing version (this repo in pre-historic, that's why this update process is so horrible 😕)

2020-12-10 14:31 UTC, dvm1984 requested changes

2020-12-10 14:31 UTC, dvm1984 commented on dist/self-service-reasons/1.0.2/cancellation-reasons_fr.json
> +          "label": "Je ne veux plus de ce produit.",
why "de" ?

2020-12-16 17:22 UTC, closed without merging