add new translations and update crowdin.yml
vtex/front.libs pull request #37
Opened 2021-09-29 17:38 UTC by camilavcoutinho

Add new translations (Bulgarian and Arabic) and update Crowdin configuration file.

Copy 1.0.7 - Copies the full 1.0.7 folder and rename it 1.0.8.

2021-10-01 14:02 UTC, lucasecdb requested changes
@camilavcoutinho I believe you need to create another folder with a new version number (like `1.0.8`) and copy and paste all the files in 1.0.7 into the new folder, and then make your modifications in this new folder

2021-10-01 14:07 UTC, camilavcoutinho commented
> @camilavcoutinho I believe you need to create another folder with a new version number (like `1.0.8`) and copy and paste all the files in 1.0.7 into the new folder, and then make your modifications in this new folder

Ohh @lucasecdb I forgot about this 😞

2021-10-01 17:13 UTC, lucasecdb approved these changes

2021-10-05 18:13 UTC, ArthurSampaio approved these changes

2021-10-05 18:24 UTC, merged